apiVersion: v1
kind: Service
metadata:
  name: {{ include "admin-side.fullname" . }}
  labels:
    {{- include "admin-side.labels" . | nindent 4 }}
  {{- with .Values.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "admin-side.selectorLabels" . | nindent 4 }}
