apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "admin-side.fullname" . }}-config
  labels:
    {{- include "admin-side.labels" . | nindent 4 }}
data:
  config.js: |
    window.__APP_CONFIG__ = {
      keycloakUrl: {{ .Values.appConfig.keycloakUrl | quote }},
      keycloakRealm: {{ .Values.appConfig.keycloakRealm | quote }},
      keycloakClientId: {{ .Values.appConfig.keycloakClientId | quote }},
      keycloakScope: {{ .Values.appConfig.keycloakScope | quote }},
      graphqlApiUrl: {{ .Values.appConfig.graphqlApiUrl | quote }},
      graphqlCacheApiUrl: {{ .Values.appConfig.graphqlCacheApiUrl | quote }},
      restApiUrl: {{ .Values.appConfig.restApiUrl | quote }},
      mediaUploadApiUrl: {{ .Values.appConfig.mediaUploadApiUrl | quote }}
    };
