apiVersion: v1
kind: Secret
metadata:
  name: {{ include "admin-side.fullname" . }}-image-pull-secrets
  labels:
    {{- include "admin-side.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
